export const PATIENT_AUTH_START = 'PATIENT_AUTH_START';
export const PATIENT_AUTH_SUCCESS = 'PATIENT_AUTH_SUCCESS';
export const PATIENT_AUTH_FAIL = 'PATIENT_AUTH_FAIL';
export const PATIENT_AUTH_LOGOUT = 'PATIENT_AUTH_LOGOUT';


export const HOSPITAL_AUTH_START = 'HOSPITAL_AUTH_START';
export const HOSPITAL_AUTH_SUCCESS = 'HOSPITAL_AUTH_SUCCESS';
export const HOSPITAL_AUTH_FAIL = 'HOSPITAL_AUTH_FAIL';
export const HOSPITAL_AUTH_LOGOUT = 'HOSPITAL_AUTH_LOGOUT';
